/****************************************************************/
/*								*/
/*   	S E   K D E F 						*/
/*								*/
/*		Keyboard Action Key Definations			*/
/*								*/
/*								*/
/*								*/
/****************************************************************/

#define ESC		0x1B

#define	KINQ		0x1D
#define	KBUY		0x1E
#define	KBUYAL		0x1F

#define KPRMENU         0xDB
#define KHELPKEY	0xDC
#define KHELPFLD	0xDE
#define	KHELPMSK	0xDF

#define	KCLEAR		0xE0
#define	KMODE		0xE1
#define	KSTOP		0xE2
#define	KSCROL		0xE3
#define	KPRINT		0xE4
#define	KBRITE		0xE5
#define	KCLRFD 		0xE6
#define	KPRREC		0xE7
#define	KPRLST		0xE8
#define	KPRSET		0xE9
#define	KXMIT		0xEA
#define KCLRMSK		0xEB
#define KBMSK		0XEC
#define KNMSK		0xED
#define KSPMENU		0xEE
#define KBSPCDEL	0xEF

#define	KF0		0xF0
#define	KF1		0xF1
#define	KF2		0xF2
#define	KF3		0xF3
#define	KF4		0xF4
#define	KF5		0XF5
#define	KF6		0xF6
#define	KF7		0xF7
#define	KF8		0xF8
#define	KF9		0xF9
#define	KBFLD		0xFA
#define	KNFLD		0xFB
#define	KBSPC		0xFC
#define	KFSPC		0xFD
#define KEXIT		0xFE

